In [2]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[3, 9, 9],
       [9, 7, 9],
       [8, 9, 7]])

In [ ]:
# understand oncagain

In [ ]:
data.sum()

np.int64(70)

In [ ]:
data.sum(axis=1)

array([21, 25, 24])

In [ ]:
data.sum(axis=0)

array([20, 25, 25])

In [ ]:
data.max(axis=1)

array([9, 9, 9])

In [ ]:
data.argmax(axis=1)    # it tell the postion of the int

array([1, 0, 1])

In [ ]:
data=np.random.randint(0,100,(10,5))        # it takes randomly 1to 100 no ,in 1o row 5 coloum

In [ ]:
data

array([[23, 82, 97,  5, 39],
       [55,  3, 47, 40, 93],
       [91, 79, 57, 19, 54],
       [96, 80, 92, 85, 27],
       [43, 86, 57, 18, 88],
       [ 5,  2, 26, 11, 97],
       [83, 90, 47, 99, 17],
       [32, 74, 65, 47, 63],
       [82, 57,  0, 57, 39],
       [ 0, 78, 93, 70, 35]])

In [ ]:
data.sum()

np.int64(2725)

In [ ]:
data.sum(axis=0)

array([510, 631, 581, 451, 552])

In [ ]:
data.sum(axis=1)

array([246, 238, 300, 380, 292, 141, 336, 281, 235, 276])

In [ ]:
data.max(axis=1)     # which is the bigger in coloum

array([97, 93, 91, 96, 88, 97, 99, 74, 82, 93])

In [ ]:
data.argmax(axis=1)        #postion of the bigger int

array([2, 4, 0, 0, 4, 4, 3, 1, 0, 2])

In [ ]:
data.sum(axis=1).argmin()+_

array([251, 243, 305, 385, 297, 146, 341, 286, 240, 281])

In [ ]:
data=np.random.randint(1000,10000,(10,6))

In [ ]:
data

array([[6408, 8285, 5800, 3828, 1635, 7999],
       [6243, 6795, 8324, 8882, 9862, 9881],
       [2990, 1245, 7940, 3605, 1901, 3615],
       [1354, 7616, 4858, 2182, 8664, 4182],
       [3819, 7741, 5808, 6037, 1776, 2083],
       [4613, 8596, 4974, 7284, 1368, 1241],
       [7546, 1881, 8187, 5891, 3093, 8037],
       [9338, 1215, 9863, 2522, 8283, 1928],
       [9837, 3009, 5980, 7421, 2602, 1127],
       [6323, 7455, 6332, 5590, 6318, 1572]])

In [ ]:
data.sum(axis=0).argmax()+1

np.int64(3)

In [ ]:
data.sum(axis=0)

array([58471, 53838, 68066, 53242, 45502, 41665])

In [ ]:
data.argmax()

np.int64(11)

In [ ]:
data

array([[6408, 8285, 5800, 3828, 1635, 7999],
       [6243, 6795, 8324, 8882, 9862, 9881],
       [2990, 1245, 7940, 3605, 1901, 3615],
       [1354, 7616, 4858, 2182, 8664, 4182],
       [3819, 7741, 5808, 6037, 1776, 2083],
       [4613, 8596, 4974, 7284, 1368, 1241],
       [7546, 1881, 8187, 5891, 3093, 8037],
       [9338, 1215, 9863, 2522, 8283, 1928],
       [9837, 3009, 5980, 7421, 2602, 1127],
       [6323, 7455, 6332, 5590, 6318, 1572]])

In [ ]:
data.sum(axis=0)[3:].sum()

np.int64(140409)

In [ ]:
data.sum(axis=0).max()-data.sum(axis=0).min()

np.int64(26401)

In [ ]:
data=np.random.randint(0,10,10)

In [ ]:
data

array([5, 0, 9, 0, 1, 9, 4, 6, 8, 5])

In [ ]:
np.median(data)

np.float64(5.0)

In [ ]:
np.quantile(data,0.25)

np.float64(1.75)

In [ ]:
np.quantile(data,0.75)

np.float64(7.5)

In [ ]:
# descriptive statistics


In [3]:
data=np.random.randint(0,10,(10,2))

In [4]:
data

array([[5, 7],
       [7, 6],
       [8, 6],
       [8, 1],
       [3, 3],
       [8, 7],
       [6, 8],
       [1, 8],
       [5, 9],
       [6, 4]])

In [11]:
v1=np.arrange(1,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [7]:
np.corrcoef(data.T)

array([[ 1.        , -0.25422776],
       [-0.25422776,  1.        ]])

In [23]:
data[:,0]=v1,
data[:,1]=v2

ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

In [13]:
v1=np.arange(1,11)

In [17]:
v1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
v2=np.arange(10,20)

In [22]:
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
data=np.random.randint(0,10,(5,5))

In [26]:
np.corrcoef(data.T)

array([[ 1.        ,  0.88080603,  0.43040529,  0.06404469,  0.27247847],
       [ 0.88080603,  1.        ,  0.5804497 , -0.35877365,  0.57818345],
       [ 0.43040529,  0.5804497 ,  1.        , -0.649313  ,  0.93391519],
       [ 0.06404469, -0.35877365, -0.649313  ,  1.        , -0.86183155],
       [ 0.27247847,  0.57818345,  0.93391519, -0.86183155,  1.        ]])