In [8]:
import numpy as np

In [9]:
list(),str(),tuple(),set(),dict()

([], '', (), set(), {})

In [18]:
y=np.array([1,2,3,])

In [22]:
x=[1,2,3]

In [23]:
type(x),type(y)

(list, numpy.ndarray)

In [24]:
y/2

array([0.5, 1. , 1.5])

In [25]:
x=[1,2,3,"data science"]
x

[1, 2, 3, 'data science']

In [26]:
type(x[0]),type(x[1]),type(x[2]),type(x[3])

(int, int, int, str)

In [27]:
y=np.array([1,2,3,"data science"])
y

array(['1', '2', '3', 'data science'], dtype='<U21')

In [28]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.str_, numpy.str_, numpy.str_, numpy.str_)

In [29]:
y

array(['1', '2', '3', 'data science'], dtype='<U21')

In [30]:
for i in range(1,10):
    print(np.random.randint(0,10))     # random no every time changes

5
2
9
5
3
1
5
8
6


In [42]:
np.random.randint(0, 10,(5,5))

array([[1, 7, 1, 9, 9],
       [7, 7, 2, 6, 5],
       [1, 6, 1, 6, 6],
       [2, 1, 7, 6, 5],
       [4, 4, 0, 1, 8]])

In [39]:
import numpy as np
data = np.arange(25).reshape(5, 5)
print(data)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [36]:
np.random.randint(10, 100,(5,5))


array([[60, 52, 42, 42, 36],
       [83, 64, 51, 40, 66],
       [36, 84, 52, 82, 75],
       [13, 75, 24, 52, 18],
       [35, 65, 72, 10, 40]])

In [37]:
data[-5:-4,-5:-4]

array([[0]])

In [40]:
data[0:3,4:5]

array([[ 4],
       [ 9],
       [14]])

In [45]:
data[0:4,2:-3]

array([], shape=(4, 0), dtype=int64)

In [46]:
data.size

25

In [49]:
data.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [50]:
x=2

In [51]:
data**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [52]:
x=np.random.randint(10,100,(5,5))
y=np.random.randint(10,100,(5,5))

In [53]:
x

array([[35, 27, 21, 68, 56],
       [26, 68, 91, 33, 43],
       [62, 62, 25, 13, 44],
       [66, 17, 69, 94, 52],
       [50, 23, 24, 74, 29]])

In [54]:
y

array([[49, 31, 45, 45, 74],
       [25, 65, 56, 11, 23],
       [18, 35, 61, 25, 19],
       [40, 50, 60, 91, 86],
       [51, 77, 48, 97, 54]])

In [55]:
np.add(x,2)

array([[37, 29, 23, 70, 58],
       [28, 70, 93, 35, 45],
       [64, 64, 27, 15, 46],
       [68, 19, 71, 96, 54],
       [52, 25, 26, 76, 31]])

In [56]:
np.floor_divide(x,2)

array([[17, 13, 10, 34, 28],
       [13, 34, 45, 16, 21],
       [31, 31, 12,  6, 22],
       [33,  8, 34, 47, 26],
       [25, 11, 12, 37, 14]])

In [57]:
np.pow(x,2)

array([[1225,  729,  441, 4624, 3136],
       [ 676, 4624, 8281, 1089, 1849],
       [3844, 3844,  625,  169, 1936],
       [4356,  289, 4761, 8836, 2704],
       [2500,  529,  576, 5476,  841]])

In [58]:
np.random.randint(0,10,(10,10))

array([[6, 0, 8, 8, 0, 8, 8, 8, 4, 3],
       [3, 3, 8, 1, 3, 1, 2, 0, 9, 9],
       [4, 9, 1, 6, 3, 4, 3, 9, 1, 7],
       [9, 2, 5, 9, 0, 6, 0, 0, 3, 5],
       [4, 4, 5, 4, 4, 0, 3, 3, 1, 9],
       [6, 7, 0, 3, 3, 1, 2, 2, 6, 9],
       [6, 4, 2, 0, 9, 8, 2, 8, 5, 0],
       [4, 8, 8, 8, 8, 9, 2, 5, 1, 9],
       [0, 6, 5, 4, 6, 0, 6, 4, 0, 0],
       [3, 7, 6, 1, 4, 1, 5, 4, 4, 9]])

In [60]:
np.random.rand(10,10)

array([[0.4409882 , 0.13636416, 0.96745425, 0.39229661, 0.96839944,
        0.34414827, 0.75025215, 0.98863973, 0.62414392, 0.71636561],
       [0.83261761, 0.80253542, 0.76927492, 0.41449093, 0.42316819,
        0.69312098, 0.26954621, 0.91456584, 0.03346795, 0.12830088],
       [0.09307116, 0.9150149 , 0.51658488, 0.100059  , 0.28624264,
        0.10024406, 0.95999146, 0.63529883, 0.97959729, 0.17035859],
       [0.57360851, 0.200644  , 0.60932139, 0.21406943, 0.60367425,
        0.27057487, 0.81083539, 0.74775532, 0.84003967, 0.05186517],
       [0.28098479, 0.21867848, 0.99172242, 0.96324069, 0.81155905,
        0.43804125, 0.96945537, 0.55208618, 0.98135926, 0.14527624],
       [0.86384646, 0.76597246, 0.77229276, 0.31741166, 0.055875  ,
        0.56192691, 0.91063778, 0.16876168, 0.72799161, 0.18726622],
       [0.27725858, 0.87666799, 0.03209821, 0.01484168, 0.54765554,
        0.86970105, 0.81239287, 0.0954765 , 0.40720057, 0.93784219],
       [0.8201123 , 0.76592   , 0.3946812

In [62]:
np.random.randn(130,130).mean()

np.float64(0.003796315373096853)

In [63]:
np.float64(0.0055653378468262)

np.float64(0.0055653378468262)

In [65]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
print(data.sum())
print(data.min())
print(data.max())

300
0
24


In [72]:
data.argmax()

np.int64(24)

In [74]:
data=np.random.randint(0,10,(3,3))

In [75]:
data

array([[4, 1, 6],
       [7, 2, 1],
       [1, 0, 3]])

In [76]:
data.sum(axis=1)

array([11, 10,  4])

In [77]:
data.sum(axis=0)

array([12,  3, 10])

In [78]:
data.min(axis=1)

array([1, 1, 0])